version: "3.3"

services:

    webapp:
        depends_on: [ db ]
        build:
          context: .
          dockerfile: Dockerfile
        command: python manage.py runserver 0.0.0.0:8080
        volumes: [ '.:/app' ]
        ports: [ '8000:8080' ]
        environment:
            DB_NAME: sql_db
            DB_HOST: db
            DB_USER: sql_user
            DB_PASSWORD: sql_pass

    db:
        image: mysql:latest
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        volumes: [ '.db_data:/var/lib/mysql' ]
        environment:
            MYSQL_ROOT_PASSWORD: sql_root_pass
            MYSQL_DATABASE: sql_db
            MYSQL_USER: sql_user
            MYSQL_PASSWORD: sql_pass
