version: '2.1'

services:

    webapp:
        depends_on:
            db:
                condition: service_healthy
        build:
          context: .
          dockerfile: Dockerfile
        command: python /app/manage.py runserver 0.0.0.0:8000
        volumes: [ '.:/app' ]
        ports: [ '8000:8000' ]
        environment:
            DB_NAME: sql_db
            DB_HOST: db
            DB_USER: sql_user
            DB_PASSWORD: sql_pass

    db:
        image: mysql:latest
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        volumes: [ '.db_data:/var/lib/mysql' ]
        environment:
            MYSQL_ROOT_PASSWORD: sql_root_pass
            MYSQL_DATABASE: sql_db
            MYSQL_USER: sql_user
            MYSQL_PASSWORD: sql_pass
        healthcheck:
            test: "mysql --host=127.0.0.1 --port=3306 --user=root --password=sql_root_pass sql_db -e 'select 1'"
            interval: 30s
            timeout: 10s
            retries: 5
