# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-10-16 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_auto_20180319_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='photo',
            field=models.FileField(null=True, upload_to='photos'),
        ),
    ]
