# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-04 22:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_auto_20180319_1832'),
        ('questions', '0005_auto_20180515_1201'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('likes', '0002_auto_20180604_2222'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('put', models.DateTimeField(auto_now=True, verbose_name='\u041f\u043e\u0441\u0442\u0430\u0432\u043b\u0435\u043d')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_like', to='questions.Answer', verbose_name='\u041e\u0442\u0432\u0435\u0442')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_like', to=settings.AUTH_USER_MODEL, verbose_name='\u0410\u0432\u0442\u043e\u0440')),
            ],
            options={
                'verbose_name': '\u041b\u0430\u0439\u043a \u043e\u0442\u0432\u0435\u0442\u0430',
                'verbose_name_plural': '\u041b\u0430\u0439\u043a\u0438 \u043e\u0442\u0432\u0435\u0442\u0430',
            },
        ),
        migrations.CreateModel(
            name='CategoryLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('put', models.DateTimeField(auto_now=True, verbose_name='\u041f\u043e\u0441\u0442\u0430\u0432\u043b\u0435\u043d')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_like', to=settings.AUTH_USER_MODEL, verbose_name='\u0410\u0432\u0442\u043e\u0440')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_like', to='categories.Category', verbose_name='\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f')),
            ],
            options={
                'verbose_name': '\u041b\u0430\u0439\u043a \u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u0438',
                'verbose_name_plural': '\u041b\u0430\u0439\u043a\u0438 \u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u0438',
            },
        ),
        migrations.CreateModel(
            name='QuestionLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('put', models.DateTimeField(auto_now=True, verbose_name='\u041f\u043e\u0441\u0442\u0430\u0432\u043b\u0435\u043d')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_like', to=settings.AUTH_USER_MODEL, verbose_name='\u0410\u0432\u0442\u043e\u0440')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_like', to='questions.Question', verbose_name='\u0412\u043e\u043f\u0440\u043e\u0441')),
            ],
            options={
                'verbose_name': '\u041b\u0430\u0439\u043a \u0432\u043e\u043f\u0440\u043e\u0441\u0430',
                'verbose_name_plural': '\u041b\u0430\u0439\u043a\u0438 \u0432\u043e\u043f\u0440\u043e\u0441\u0430',
            },
        ),
        migrations.RemoveField(
            model_name='like',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='like',
            name='author',
        ),
        migrations.RemoveField(
            model_name='like',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='like',
            name='question',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
