# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-05 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0003_auto_20180604_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorylike',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='\u0423\u0434\u0430\u043b\u0435\u043d'),
        ),
    ]
