# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-05 14:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0005_auto_20180605_0939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answerlike',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='categorylike',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='questionlike',
            name='is_deleted',
        ),
    ]
